from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from fraud_pipeline import PCA_FEATURES, PROJECT_ROOT, TARGET, run_pipeline


def make_smoke_fixture(path: Path, seed: int = 7) -> Path:
    rng = np.random.default_rng(seed)
    rows = 2600
    frauds = 90
    labels = np.zeros(rows, dtype=int)
    fraud_idx = rng.choice(rows, size=frauds, replace=False)
    labels[fraud_idx] = 1

    frame = pd.DataFrame({"Time": np.sort(rng.uniform(0, 172800, size=rows))})
    for feature in PCA_FEATURES:
        frame[feature] = rng.normal(0, 1, size=rows)

    legitimate_amount = rng.gamma(shape=2.0, scale=28.0, size=rows)
    fraud_amount = rng.gamma(shape=5.0, scale=58.0, size=rows)
    amount = np.where(labels == 1, fraud_amount, legitimate_amount)
    amount[rng.choice(rows, size=60, replace=False)] = 0.0

    frame["V3"] += labels * 1.1
    frame["V4"] += labels * 2.2
    frame["V10"] -= labels * 2.0
    frame["V14"] -= labels * 3.3
    frame["V17"] -= labels * 2.4
    frame["Amount"] = amount
    frame[TARGET] = labels

    frame = frame.sample(frac=1.0, random_state=seed).reset_index(drop=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, index=False)
    return path


def main() -> int:
    sample_path = PROJECT_ROOT / "data" / "sample" / "smoke_transactions.csv"
    make_smoke_fixture(sample_path)
    result = run_pipeline(
        raw_path=sample_path,
        output_dir=PROJECT_ROOT / "_smoke_validation",
        data_url="local smoke fixture generated by src/smoke_test.py; not the real Kaggle/ULB dataset",
        download=False,
        split="stratified",
        epochs=35,
        seed=7,
        threshold_policy="f2",
    )
    test_metrics = result["champion_result"]["test"]
    if test_metrics["recall"] < 0.70 or test_metrics["average_precision"] < 0.70:
        raise AssertionError(f"Smoke metrics too weak: {test_metrics}")
    print("Smoke test passed")
    print(f"Champion: {result['champion_name']}")
    print(f"Test precision: {test_metrics['precision']:.4f}")
    print(f"Test recall: {test_metrics['recall']:.4f}")
    print(f"Report: {result['report_path']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
